name: Publish Package

on:
  workflow_dispatch:
    inputs:
      pypi_repo:
        description: "Repo to upload to pypi"
        default: "testpypi"
        required: true

jobs:
  python-build-n-publish:
    name: unit_curious
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Initialize Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install twine
         
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Build binary wheel and a source tarball
        run: python setup.py sdist

      - name: Publish to Test PyPI
        if: github.event.inputs.pypi_repo == 'testpypi'
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/* --skip-existing
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: Publish to PyPI
        if: github.event.inputs.pypi_repo == 'pypi'
        run: |
          twine upload dist/* --skip-existing
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}